package com.example.tourismmedia.ui.detail;

import android.os.Bundle;import android.view.View;import android.widget.*;import androidx.annotation.NonNull;import androidx.fragment.app.Fragment;import androidx.navigation.Navigation;import com.bumptech.glide.Glide;import com.example.tourismmedia.R;import com.example.tourismmedia.data.AppRepository;import com.example.tourismmedia.data.model.AppModels.*;

public class DetailFragment extends Fragment {
 private static final String CHALLENGE_IMAGE="https://media-cdn-v2.laodong.vn/Storage/NewsPortal/2023/3/16/1158477/IMG_8725-2.jpg";private AppRepository repo;private ImageView image;private TextView type,title,meta,description,extra;private Button primary,secondary;private ProgressBar progress;private long id;private String resourceType;
 public DetailFragment(){super(R.layout.fragment_detail);}
 @Override public void onViewCreated(@NonNull View v,Bundle b){repo=AppRepository.get(requireContext());image=v.findViewById(R.id.detail_image);type=v.findViewById(R.id.detail_type);title=v.findViewById(R.id.detail_title);meta=v.findViewById(R.id.detail_meta);description=v.findViewById(R.id.detail_description);extra=v.findViewById(R.id.detail_extra);primary=v.findViewById(R.id.detail_primary);secondary=v.findViewById(R.id.detail_secondary);progress=v.findViewById(R.id.detail_progress);v.findViewById(R.id.detail_back).setOnClickListener(x->Navigation.findNavController(v).navigateUp());Bundle args=getArguments();id=args==null?0:args.getLong("id");resourceType=args==null?"location":args.getString("type","location");load();}
 private void load(){switch(resourceType){case "trip":repo.trip(id,(x,e,s)->{if(x==null){error(e);return;}bind("TRIP",x.title,"★ "+x.rating+" · "+x.reviewCount+" reviews",x.description,"Estimated cost: "+String.format("%,d VND",x.estimatedPrice)+"\nDuration: "+x.totalTime+" minutes\nHighlights: "+safe(x.highlight),x.imageUrl,"♡ Save trip",null);secondary.setVisibility(View.GONE);primary.setOnClickListener(v->repo.favoriteTrip(id,this::action));});break;case "challenge":repo.challenge(id,(x,e,s)->{if(x==null){error(e);return;}int target=x.target>0?x.target:x.requiredCheckins;bind("CHALLENGE",x.name,"+"+x.rewardPoint+" points",x.description,"Progress: "+x.progress+"/"+target+"\nType: "+safe(x.challengeType)+"\nRuns: "+safe(x.startDate)+" → "+safe(x.endDate),CHALLENGE_IMAGE,"Join challenge",null);secondary.setVisibility(View.GONE);primary.setOnClickListener(v->repo.joinChallenge(id,this::action));});break;case "reward":repo.reward(id,(x,e,s)->{if(x==null){error(e);return;}bind("REWARD",x.name,x.cost+" points",x.description,"Discount: "+x.percent+"%",CHALLENGE_IMAGE,"Redeem reward",null);secondary.setVisibility(View.GONE);primary.setOnClickListener(v->repo.redeem(id,this::action));});break;default:repo.location(id,(x,e,s)->{if(x==null){error(e);return;}bind("PLACE",x.name,"★ "+x.rating+" · "+x.reviewCount+" reviews",x.description,"⌖ "+safe(x.address)+"\n"+safe(x.city)+"\nOpening hours: "+safe(x.openingHours)+" – "+safe(x.closingHours)+"\nPrice: "+(x.price==0?"Free":String.format("%,.0f VND",x.price))+"\nHighlights: "+safe(x.highlights),x.imageUrl,"Check in","♡ Save to favourites");primary.setOnClickListener(v->repo.checkIn(id,this::action));secondary.setOnClickListener(v->repo.favoriteLocation(id,x.favorite==1,this::action));});}}
 private void bind(String label,String heading,String metadata,String body,String more,String url,String primaryText,String secondaryText){if(!isAdded())return;progress.setVisibility(View.GONE);type.setText(label);title.setText(heading);meta.setText(metadata);description.setText(safe(body));extra.setText(more);primary.setText(primaryText);if(secondaryText!=null)secondary.setText(secondaryText);Glide.with(requireContext()).load(url).centerCrop().placeholder(R.drawable.bg_hero).error(R.drawable.bg_hero).into(image);}
 private void action(Message m,String e,boolean sample){Toast.makeText(requireContext(),e!=null?e:(m==null?"Done":m.message),Toast.LENGTH_SHORT).show();}
 private void error(String message){progress.setVisibility(View.GONE);title.setText("Could not load this content");description.setText(message);primary.setVisibility(View.GONE);secondary.setVisibility(View.GONE);}
 private String safe(String value){return value==null||value.isBlank()?"Not available":value;}
}
