package com.example.tourismmedia.ui.home;

import android.os.Bundle;import android.view.View;import android.widget.*;import androidx.annotation.NonNull;import androidx.fragment.app.Fragment;import androidx.navigation.Navigation;import androidx.recyclerview.widget.*;import com.bumptech.glide.Glide;import com.example.tourismmedia.R;import com.example.tourismmedia.data.AppRepository;import com.example.tourismmedia.data.model.AppModels.Location;import com.example.tourismmedia.ui.common.SimpleCardAdapter;import java.util.*;

public class HomeFragment extends Fragment {
 public HomeFragment(){super(R.layout.fragment_home);}
 @Override public void onViewCreated(@NonNull View v,Bundle b){AppRepository repo=AppRepository.get(requireContext());ImageView hero=v.findViewById(R.id.home_hero_image);((TextView)v.findViewById(R.id.home_greeting)).setText("Tourism Media");String username=repo.session().username();((TextView)v.findViewById(R.id.home_avatar)).setText(username==null||username.isBlank()?"TM":username.substring(0,1).toUpperCase());v.findViewById(R.id.home_avatar).setOnClickListener(x->Navigation.findNavController(v).navigate(R.id.profileFragment));v.findViewById(R.id.home_explore).setOnClickListener(x->Navigation.findNavController(v).navigate(R.id.exploreFragment));RecyclerView list=v.findViewById(R.id.home_list);list.setLayoutManager(new LinearLayoutManager(requireContext()));SimpleCardAdapter adapter=new SimpleCardAdapter(item->showLocation((Location)item.value));list.setAdapter(adapter);repo.locations("",(data,error,sample)->{if(!isAdded()||getView()!=v)return;List<SimpleCardAdapter.CardItem> cards=new ArrayList<>();for(Location x:data.subList(0,Math.min(4,data.size())))cards.add(new SimpleCardAdapter.CardItem("⌖",x.name,safe(x.type)+" · "+safe(x.city),"★ "+x.rating,x.imageUrl,x));adapter.submit(cards);if(!data.isEmpty())Glide.with(requireContext()).load(data.get(0).imageUrl).centerCrop().placeholder(R.drawable.bg_hero).error(R.drawable.bg_hero).into(hero);});}
 private void showLocation(Location x){Bundle args=new Bundle();args.putString("type","location");args.putLong("id",x.id);Navigation.findNavController(requireView()).navigate(R.id.detailFragment,args);}
 private String safe(String s){return s==null?"":s;}
}
