package com.example.tourismmedia.ui.profile;

import android.os.Bundle;import android.view.View;import android.widget.*;import androidx.annotation.NonNull;import androidx.fragment.app.Fragment;import androidx.navigation.Navigation;import androidx.recyclerview.widget.*;import com.example.tourismmedia.R;import com.example.tourismmedia.data.AppRepository;import com.example.tourismmedia.data.model.AppModels.*;import com.example.tourismmedia.ui.common.SimpleCardAdapter;import java.util.*;

public class AccountCollectionFragment extends Fragment {
 private AppRepository repo;private SimpleCardAdapter adapter;private TextView title,subtitle,status,emptyText;private View empty,list;private String mode;
 public AccountCollectionFragment(){super(R.layout.fragment_account_collection);}
 @Override public void onViewCreated(@NonNull View v,Bundle b){repo=AppRepository.get(requireContext());title=v.findViewById(R.id.collection_title);subtitle=v.findViewById(R.id.collection_subtitle);status=v.findViewById(R.id.collection_status);empty=v.findViewById(R.id.collection_empty);emptyText=v.findViewById(R.id.collection_empty_text);list=v.findViewById(R.id.collection_list);RecyclerView recycler=(RecyclerView)list;recycler.setLayoutManager(new LinearLayoutManager(requireContext()));adapter=new SimpleCardAdapter(this::open);recycler.setAdapter(adapter);v.findViewById(R.id.collection_back).setOnClickListener(x->Navigation.findNavController(v).navigateUp());mode=getArguments()==null?"favorite_locations":getArguments().getString("mode","favorite_locations");load();}
 private void load(){switch(mode){case "favorite_trips":title.setText("Chuyến đi đã lưu");subtitle.setText("Những hành trình bạn muốn khám phá");repo.favoriteTrips((data,e,s)->showTrips(data,e));break;case "checkins":title.setText("Lịch sử check-in");subtitle.setText("Dấu chân du lịch của bạn");repo.checkIns((data,e,s)->showLocations(data,e,true));break;case "vouchers":title.setText("Voucher của tôi");subtitle.setText("Phần thưởng đã đổi từ điểm");repo.vouchers((data,e,s)->showVouchers(data,e));break;default:title.setText("Địa điểm đã lưu");subtitle.setText("Bộ sưu tập điểm đến yêu thích");repo.favoriteLocations((data,e,s)->showLocations(data,e,false));}}
 private void showLocations(List<Location> data,String error,boolean checkin){List<SimpleCardAdapter.CardItem> cards=new ArrayList<>();for(Location x:data)cards.add(new SimpleCardAdapter.CardItem("⌖",x.name,safe(x.category)+" · "+safe(x.city),checkin?"Check-in: "+date(x.checkedInAt):"★ "+x.rating+" · Đã lưu",x.imageUrl,x));show(cards,error,checkin?"Bạn chưa check-in địa điểm nào":"Bạn chưa lưu địa điểm nào");}
 private void showTrips(List<Trip> data,String error){List<SimpleCardAdapter.CardItem> cards=new ArrayList<>();for(Trip x:data)cards.add(new SimpleCardAdapter.CardItem("♧",x.title,safe(x.description),"★ "+x.rating+" · "+String.format("%,dđ",x.estimatedPrice),x.imageUrl,x));show(cards,error,"Bạn chưa lưu chuyến đi nào");}
 private void showVouchers(List<Voucher> data,String error){List<SimpleCardAdapter.CardItem> cards=new ArrayList<>();for(Voucher x:data)cards.add(new SimpleCardAdapter.CardItem("🎟",x.name,safe(x.description),x.percent+"% · Mã: "+safe(x.code)+" · "+safe(x.status),x));show(cards,error,"Bạn chưa có voucher nào");}
 private void show(List<SimpleCardAdapter.CardItem> cards,String error,String emptyMessage){adapter.submit(cards);status.setText(error!=null?error:cards.size()+" mục · dữ liệu từ backend");boolean none=cards.isEmpty();empty.setVisibility(none?View.VISIBLE:View.GONE);list.setVisibility(none?View.GONE:View.VISIBLE);emptyText.setText(error!=null?"Không tải được dữ liệu":emptyMessage);}
 private void open(SimpleCardAdapter.CardItem item){Bundle args=new Bundle();if(item.value instanceof Location){args.putString("type","location");args.putLong("id",((Location)item.value).id);}else if(item.value instanceof Trip){args.putString("type","trip");args.putLong("id",((Trip)item.value).id);}else if(item.value instanceof Voucher){args.putString("type","reward");args.putLong("id",((Voucher)item.value).rewardId);}else return;Navigation.findNavController(requireView()).navigate(R.id.detailFragment,args);}
 private String safe(String value){return value==null||value.isBlank()?"Chưa có thông tin":value;}
 private String date(String value){if(value==null)return "Chưa rõ";return value.replace('T',' ').replace("Z","");}
}
