package com.example.tourismmedia.ui.profile;

import android.content.Intent;import android.os.Bundle;import android.view.View;import android.widget.*;import androidx.annotation.NonNull;import androidx.fragment.app.Fragment;import com.bumptech.glide.Glide;import com.example.tourismmedia.R;import com.example.tourismmedia.auth.AuthActivity;import com.example.tourismmedia.data.AppRepository;

public class ProfileFragment extends Fragment {
 private static final String COVER="https://www.homepaylater.vn/static/88357cc22dcb6460df003e4ff1dec446/9d72c/1_khu_du_lich_binh_quoi_2_mang_den_khong_gian_thu_gian_hoa_minh_vao_thien_nhien_299b8d9efd.jpg";private AppRepository repo;private TextView name,email,points,avatar;
 public ProfileFragment(){super(R.layout.fragment_profile);}
 @Override public void onViewCreated(@NonNull View v,Bundle b){repo=AppRepository.get(requireContext());Glide.with(this).load(COVER).centerCrop().placeholder(R.drawable.bg_hero).error(R.drawable.bg_hero).into((ImageView)v.findViewById(R.id.profile_cover));name=v.findViewById(R.id.profile_name);email=v.findViewById(R.id.profile_email);points=v.findViewById(R.id.profile_points);avatar=v.findViewById(R.id.profile_avatar);load();v.findViewById(R.id.edit_profile).setOnClickListener(x->edit());v.findViewById(R.id.profile_saved).setOnClickListener(x->saved());v.findViewById(R.id.profile_checkins).setOnClickListener(x->open("checkins"));v.findViewById(R.id.profile_vouchers).setOnClickListener(x->open("vouchers"));v.findViewById(R.id.logout_button).setOnClickListener(x->{repo.session().clear();startActivity(new Intent(requireContext(),AuthActivity.class));requireActivity().finish();});}
 private void load(){repo.profile((p,e,s)->{if(p==null){toast(e==null?"Could not load your profile from the backend":e);return;}name.setText(p.username);email.setText(p.email);points.setText(String.format("%,d\nPoints",p.points));String username=p.username==null||p.username.trim().isEmpty()?"Traveller":p.username.trim();String[] words=username.split(" ");String initials=words[0].substring(0,1);if(words.length>1)initials+=words[words.length-1].substring(0,1);avatar.setText(initials.toUpperCase());});}
 private void edit(){EditText input=new EditText(requireContext());input.setText(name.getText());new androidx.appcompat.app.AlertDialog.Builder(requireContext()).setTitle("Display name").setView(input).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{String next=input.getText().toString().trim();if(next.length()<3){toast("Name must be at least 3 characters");return;}repo.updateProfile(next,(message,error,sample)->{if(error==null){name.setText(next);toast(message);}else toast(error);});}).show();}
 private void saved(){String[] choices={"Saved places","Saved trips"};new androidx.appcompat.app.AlertDialog.Builder(requireContext()).setTitle("Saved content").setItems(choices,(d,i)->open(i==0?"favorite_locations":"favorite_trips")).setNegativeButton("Close",null).show();}
 private void open(String mode){Bundle args=new Bundle();args.putString("mode",mode);androidx.navigation.Navigation.findNavController(requireView()).navigate(R.id.accountCollectionFragment,args);}
 private void toast(String s){Toast.makeText(requireContext(),s,Toast.LENGTH_SHORT).show();}
}
