package com.example.tourismmedia.ui.trips;

import android.os.Bundle;import android.text.*;import android.view.View;import android.widget.*;import androidx.annotation.NonNull;import androidx.appcompat.app.AlertDialog;import androidx.fragment.app.Fragment;import androidx.navigation.Navigation;import androidx.recyclerview.widget.*;import com.example.tourismmedia.R;import com.example.tourismmedia.data.AppRepository;import com.example.tourismmedia.data.model.AppModels.Trip;import com.example.tourismmedia.ui.common.SimpleCardAdapter;import java.util.*;

public class TripsFragment extends Fragment {
 private static final String[] SORT_LABELS={"Highest rated","Newest","Price: low to high","Price: high to low","Shortest first","Name: A-Z"};private static final String[] SORT_VALUES={"rating-desc","id-desc","estimate_price-asc","estimate_price-desc","total_time-asc","title-asc"};
 private AppRepository repo;private SimpleCardAdapter adapter;private String query="",sort="rating-desc";private Double minRating=null;private Long maxPrice=null;private Button filterButton,sortButton;
 public TripsFragment(){super(R.layout.fragment_trips);}
 @Override public void onViewCreated(@NonNull View v,Bundle b){repo=AppRepository.get(requireContext());RecyclerView list=v.findViewById(R.id.trips_list);list.setLayoutManager(new LinearLayoutManager(requireContext()));adapter=new SimpleCardAdapter(i->details((Trip)i.value));list.setAdapter(adapter);filterButton=v.findViewById(R.id.trips_filter);sortButton=v.findViewById(R.id.trips_sort);filterButton.setOnClickListener(x->filter());sortButton.setOnClickListener(x->sort());v.findViewById(R.id.add_trip).setOnClickListener(x->create());((EditText)v.findViewById(R.id.trips_search)).addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){query=s.toString();load();}public void afterTextChanged(Editable e){}});load();}
 private void load(){repo.trips(query,minRating,maxPrice,sort,(data,e,s)->{List<SimpleCardAdapter.CardItem> cards=new ArrayList<>();for(Trip x:data)cards.add(new SimpleCardAdapter.CardItem("♧",x.title,safe(x.description),"★ "+x.rating+" · "+String.format("%,d VND",x.estimatedPrice)+" · "+x.totalTime+" minutes",x.imageUrl,x));adapter.submit(cards);if(e!=null)Toast.makeText(requireContext(),e,Toast.LENGTH_SHORT).show();});}
 private void filter(){LinearLayout form=new LinearLayout(requireContext());form.setOrientation(LinearLayout.VERTICAL);form.setPadding(44,8,44,0);Spinner rating=new Spinner(requireContext());String[] ratings={"Any rating","3 stars and up","4 stars and up","4.5 stars and up"};rating.setAdapter(new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_dropdown_item,ratings));if(minRating!=null)rating.setSelection(minRating==3?1:minRating==4?2:3);form.addView(rating);EditText price=new EditText(requireContext());price.setHint("Maximum budget");price.setInputType(2);if(maxPrice!=null)price.setText(String.valueOf(maxPrice));form.addView(price);new AlertDialog.Builder(requireContext()).setTitle("Filter trips").setView(form).setNeutralButton("Clear",(d,w)->{minRating=null;maxPrice=null;filterButton.setText("⚙ Filters");load();}).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{double[] values={0,3,4,4.5};minRating=rating.getSelectedItemPosition()==0?null:values[rating.getSelectedItemPosition()];try{maxPrice=price.getText().toString().isBlank()?null:Long.valueOf(price.getText().toString());}catch(Exception ignored){maxPrice=null;}filterButton.setText("⚙ Filtered");load();}).show();}
 private void sort(){new AlertDialog.Builder(requireContext()).setTitle("Sort trips").setSingleChoiceItems(SORT_LABELS,indexOf(SORT_VALUES,sort),(d,i)->{sort=SORT_VALUES[i];sortButton.setText("⇅ "+SORT_LABELS[i]);d.dismiss();load();}).show();}
 private int indexOf(String[] a,String x){for(int i=0;i<a.length;i++)if(a[i].equals(x))return i;return 0;}
 private void details(Trip x){Bundle args=new Bundle();args.putString("type","trip");args.putLong("id",x.id);Navigation.findNavController(requireView()).navigate(R.id.detailFragment,args);}
 private void create(){LinearLayout form=new LinearLayout(requireContext());form.setOrientation(LinearLayout.VERTICAL);form.setPadding(42,10,42,0);EditText title=new EditText(requireContext());title.setHint("Trip name");EditText desc=new EditText(requireContext());desc.setHint("Short description");form.addView(title);form.addView(desc);new AlertDialog.Builder(requireContext()).setTitle("Create a new trip").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{if(title.getText().toString().trim().isEmpty()){Toast.makeText(requireContext(),"Please enter a name",Toast.LENGTH_SHORT).show();return;}repo.createTrip(title.getText().toString(),desc.getText().toString(),(trip,e,s)->{Toast.makeText(requireContext(),e==null?"Draft created":"Error: "+e,Toast.LENGTH_SHORT).show();if(e==null)load();});}).show();}
 private String safe(String s){return s==null?"":s;}
}
